FROM maven:3.8.4-openjdk-8
COPY . .
# CMD ["mvn", "tomcat7:run"]
ENV AZURE_TENANT_ID="YOUR_AZURE_TENANT_ID"
ENV AZURE_CLIENT_ID="YOUR_AZURE_CLIENT_ID"
ENV AZURE_CLIENT_SECRET="YOUR_AZURE_CLIENT_SECRET"
ENV SERVICE_BUS_FULLY_QUALIFIED_NAMESPACE="sb-tomcatonazure-demo-eastus-001.servicebus.windows.net"
CMD ["sh", "-c", "mvn clean package && mvn tomcat7:run"]